services:
  postgres:
    image: postgres:16-alpine
    container_name: posinvent-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: posinvent_db
      POSTGRES_USER: posinvent
      POSTGRES_PASSWORD: posinvent123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
