package co.posinvent.domain.model;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

public record CompanyConfig(
    Long id,
    String companyName,
    String nit,
    String address,
    String phone,
    String email,
    String economicActivity,
    String personType,
    String commonName,
    boolean manejaAiu,
    List<String> taxResponsibilityCodes,
    List<String> fiscalResponsibilityCodes,
    List<String> taxCodes,
    java.math.BigDecimal icaRate,
    String currency,
    UUID mainWarehouseId,
    String logoUrl,
    java.math.BigDecimal moratoryInterestRate,
    Integer interestGraceDays,
    String interestCompoundFrequency,
    String costingMethod,
    String overheadAllocationBase,
    java.math.BigDecimal overheadRate,
    java.util.UUID dianResolutionId,
    String softwarePin,
    java.util.UUID certificateId,
    java.util.UUID legalRepresentativeIdentificationTypeId,
    String legalRepresentativeDocumentNumber,
    String legalRepresentativeName,
    String legalRepresentativePosition,
    String legalRepresentativeAddress,
    String legalRepresentativeEmail,
    boolean autoGenerateJournalEntries,
    java.math.BigDecimal purchaseRetefuenteRate,
    OffsetDateTime createdAt,
    OffsetDateTime updatedAt
) {}
