-- ============================================================
-- V101: Seed de actividades económicas CIIU Rev. 4 A.C. (DIAN).
-- Catálogo comprehensivo por sección. Completable con el listado
-- oficial completo de la DIAN si se requiere la totalidad.
-- ============================================================

INSERT INTO ciiu_activities (id, code, name) VALUES
  -- A. Agricultura, ganadería, caza, silvicultura y pesca
  (gen_random_uuid(), '0111', 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas'),
  (gen_random_uuid(), '0112', 'Cultivo de arroz'),
  (gen_random_uuid(), '0113', 'Cultivo de hortalizas, raíces y tubérculos'),
  (gen_random_uuid(), '0114', 'Cultivo de tabaco'),
  (gen_random_uuid(), '0115', 'Cultivo de plantas textiles'),
  (gen_random_uuid(), '0119', 'Otros cultivos transitorios n.c.p.'),
  (gen_random_uuid(), '0121', 'Cultivo de frutas tropicales y subtropicales'),
  (gen_random_uuid(), '0122', 'Cultivo de plátano y banano'),
  (gen_random_uuid(), '0123', 'Cultivo de café'),
  (gen_random_uuid(), '0124', 'Cultivo de caña de azúcar'),
  (gen_random_uuid(), '0125', 'Cultivo de flor de corte'),
  (gen_random_uuid(), '0126', 'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos'),
  (gen_random_uuid(), '0127', 'Cultivo de cacao'),
  (gen_random_uuid(), '0128', 'Cultivo de especias y plantas aromáticas, medicinales y farmacéuticas'),
  (gen_random_uuid(), '0129', 'Otros cultivos permanentes n.c.p.'),
  (gen_random_uuid(), '0130', 'Propagación de plantas (actividades de los viveros, excepto viveros forestales)'),
  (gen_random_uuid(), '0141', 'Cría de ganado bovino y búfalos'),
  (gen_random_uuid(), '0142', 'Cría de caballos y otros equinos'),
  (gen_random_uuid(), '0143', 'Cría de ovejas y cabras'),
  (gen_random_uuid(), '0144', 'Cría de ganado porcino'),
  (gen_random_uuid(), '0145', 'Cría de aves de corral'),
  (gen_random_uuid(), '0149', 'Cría de otros animales n.c.p.'),
  (gen_random_uuid(), '0150', 'Explotación mixta (agrícola y pecuaria)'),
  (gen_random_uuid(), '0161', 'Actividades de apoyo a la agricultura'),
  (gen_random_uuid(), '0162', 'Actividades de apoyo a la ganadería'),
  (gen_random_uuid(), '0163', 'Actividades poscosecha'),
  (gen_random_uuid(), '0164', 'Tratamiento de semillas para propagación'),
  (gen_random_uuid(), '0170', 'Caza ordinaria y mediante trampas y actividades de servicios conexas'),
  (gen_random_uuid(), '0210', 'Silvicultura y otras actividades forestales'),
  (gen_random_uuid(), '0220', 'Extracción de madera'),
  (gen_random_uuid(), '0230', 'Recolección de productos forestales diferentes a la madera'),
  (gen_random_uuid(), '0240', 'Servicios de apoyo a la silvicultura'),
  (gen_random_uuid(), '0311', 'Pesca marítima'),
  (gen_random_uuid(), '0312', 'Pesca de agua dulce'),
  (gen_random_uuid(), '0321', 'Acuicultura marítima'),
  (gen_random_uuid(), '0322', 'Acuicultura de agua dulce'),

  -- B. Explotación de minas y canteras
  (gen_random_uuid(), '0510', 'Extracción de hulla (carbón de piedra)'),
  (gen_random_uuid(), '0520', 'Extracción de carbón lignito'),
  (gen_random_uuid(), '0610', 'Extracción de petróleo crudo'),
  (gen_random_uuid(), '0620', 'Extracción de gas natural'),
  (gen_random_uuid(), '0710', 'Extracción de minerales de hierro'),
  (gen_random_uuid(), '0721', 'Extracción de minerales de uranio y de torio'),
  (gen_random_uuid(), '0722', 'Extracción de oro y otros metales preciosos'),
  (gen_random_uuid(), '0729', 'Extracción de otros minerales metalíferos no ferrosos n.c.p.'),
  (gen_random_uuid(), '0811', 'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita'),
  (gen_random_uuid(), '0812', 'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas'),
  (gen_random_uuid(), '0891', 'Extracción de minerales para la fabricación de abonos y productos químicos'),
  (gen_random_uuid(), '0892', 'Extracción de halita (sal)'),
  (gen_random_uuid(), '0899', 'Extracción de otros minerales no metálicos n.c.p.'),
  (gen_random_uuid(), '0910', 'Actividades de apoyo para la extracción de petróleo y de gas natural'),
  (gen_random_uuid(), '0990', 'Actividades de apoyo para otras actividades de explotación de minas y canteras'),

  -- C. Industrias manufactureras
  (gen_random_uuid(), '1011', 'Procesamiento y conservación de carne y productos cárnicos'),
  (gen_random_uuid(), '1012', 'Procesamiento y conservación de pescados, crustáceos y moluscos'),
  (gen_random_uuid(), '1020', 'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos'),
  (gen_random_uuid(), '1030', 'Elaboración de productos lácteos'),
  (gen_random_uuid(), '1040', 'Elaboración de productos de molinería, almidones y productos derivados del almidón'),
  (gen_random_uuid(), '1051', 'Elaboración de productos de panadería'),
  (gen_random_uuid(), '1052', 'Elaboración de cacao, chocolate y productos de confitería'),
  (gen_random_uuid(), '1061', 'Trilla de café'),
  (gen_random_uuid(), '1062', 'Descafeinado, tostión y molienda del café'),
  (gen_random_uuid(), '1071', 'Elaboración y refinación de azúcar'),
  (gen_random_uuid(), '1072', 'Elaboración de panela'),
  (gen_random_uuid(), '1081', 'Elaboración de alimentos preparados para animales'),
  (gen_random_uuid(), '1082', 'Elaboración de productos alimenticios n.c.p.'),
  (gen_random_uuid(), '1089', 'Elaboración de otros productos alimenticios n.c.p.'),
  (gen_random_uuid(), '1090', 'Elaboración de alimentos preparados para animales'),
  (gen_random_uuid(), '1101', 'Destilación, rectificación y mezcla de bebidas alcohólicas'),
  (gen_random_uuid(), '1102', 'Elaboración de bebidas fermentadas no destiladas'),
  (gen_random_uuid(), '1103', 'Producción de malta, elaboración de cervezas y otras bebidas malteadas'),
  (gen_random_uuid(), '1104', 'Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas'),
  (gen_random_uuid(), '1200', 'Elaboración de productos de tabaco'),
  (gen_random_uuid(), '1311', 'Preparación e hilatura de fibras textiles'),
  (gen_random_uuid(), '1312', 'Tejeduría de productos textiles'),
  (gen_random_uuid(), '1313', 'Acabado de productos textiles'),
  (gen_random_uuid(), '1391', 'Fabricación de tejidos de punto y ganchillo'),
  (gen_random_uuid(), '1392', 'Confección de artículos con materiales textiles, excepto prendas de vestir'),
  (gen_random_uuid(), '1393', 'Fabricación de tapetes y alfombras para pisos'),
  (gen_random_uuid(), '1394', 'Fabricación de cuerdas, cordeles, cables, bramantes y redes'),
  (gen_random_uuid(), '1399', 'Fabricación de otros artículos textiles n.c.p.'),
  (gen_random_uuid(), '1410', 'Confección de prendas de vestir, excepto prendas de piel'),
  (gen_random_uuid(), '1420', 'Fabricación de artículos de piel'),
  (gen_random_uuid(), '1430', 'Fabricación de artículos de punto y ganchillo'),
  (gen_random_uuid(), '1511', 'Curtido y recurtido de cueros; recurtido y teñido de pieles'),
  (gen_random_uuid(), '1512', 'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero'),
  (gen_random_uuid(), '1521', 'Fabricación de calzado de cuero y piel, con cualquier tipo de suela'),
  (gen_random_uuid(), '1522', 'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel'),
  (gen_random_uuid(), '1523', 'Fabricación de partes del calzado'),
  (gen_random_uuid(), '1610', 'Aserrado, acepillado e impregnación de la madera'),
  (gen_random_uuid(), '1620', 'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles'),
  (gen_random_uuid(), '1630', 'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción'),
  (gen_random_uuid(), '1640', 'Fabricación de recipientes de madera'),
  (gen_random_uuid(), '1690', 'Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería'),
  (gen_random_uuid(), '1701', 'Fabricación de pulpas (pastas) celulósicas; papel y cartón'),
  (gen_random_uuid(), '1702', 'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón'),
  (gen_random_uuid(), '1709', 'Fabricación de otros artículos de papel y cartón'),
  (gen_random_uuid(), '1811', 'Actividades de impresión'),
  (gen_random_uuid(), '1812', 'Actividades de servicios relacionados con la impresión'),
  (gen_random_uuid(), '1820', 'Producción de copias a partir de grabaciones originales'),
  (gen_random_uuid(), '1910', 'Fabricación de productos de hornos de coque'),
  (gen_random_uuid(), '1921', 'Fabricación de productos de la refinación del petróleo'),
  (gen_random_uuid(), '1922', 'Mezcla de combustibles'),
  (gen_random_uuid(), '2011', 'Fabricación de sustancias y productos químicos básicos'),
  (gen_random_uuid(), '2012', 'Fabricación de abonos y compuestos inorgánicos nitrogenados'),
  (gen_random_uuid(), '2013', 'Fabricación de plásticos en formas primarias'),
  (gen_random_uuid(), '2014', 'Fabricación de caucho sintético en formas primarias'),
  (gen_random_uuid(), '2021', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario'),
  (gen_random_uuid(), '2022', 'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas'),
  (gen_random_uuid(), '2023', 'Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador'),
  (gen_random_uuid(), '2029', 'Fabricación de otros productos químicos n.c.p.'),
  (gen_random_uuid(), '2030', 'Fabricación de fibras sintéticas y artificiales'),
  (gen_random_uuid(), '2100', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos'),
  (gen_random_uuid(), '2211', 'Fabricación de llantas y neumáticos de caucho; reconstrucción de llantas'),
  (gen_random_uuid(), '2219', 'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.'),
  (gen_random_uuid(), '2221', 'Fabricación de formas básicas de plástico'),
  (gen_random_uuid(), '2229', 'Fabricación de artículos de plástico n.c.p.'),
  (gen_random_uuid(), '2310', 'Fabricación de vidrio y productos de vidrio'),
  (gen_random_uuid(), '2391', 'Fabricación de productos refractarios'),
  (gen_random_uuid(), '2392', 'Fabricación de materiales de arcilla para la construcción'),
  (gen_random_uuid(), '2393', 'Fabricación de otros productos de cerámica y porcelana'),
  (gen_random_uuid(), '2394', 'Fabricación de cemento, cal y yeso'),
  (gen_random_uuid(), '2395', 'Fabricación de artículos de hormigón, cemento y yeso'),
  (gen_random_uuid(), '2396', 'Corte, tallado y acabado de la piedra'),
  (gen_random_uuid(), '2399', 'Fabricación de otros productos minerales no metálicos n.c.p.'),
  (gen_random_uuid(), '2410', 'Industrias básicas de hierro y acero'),
  (gen_random_uuid(), '2420', 'Industrias básicas de metales preciosos y de metales no ferrosos'),
  (gen_random_uuid(), '2431', 'Fundición de hierro y de acero'),
  (gen_random_uuid(), '2432', 'Fundición de metales no ferrosos'),
  (gen_random_uuid(), '2511', 'Fabricación de productos metálicos para uso estructural'),
  (gen_random_uuid(), '2512', 'Fabricación de tanques, depósitos y recipientes de metal'),
  (gen_random_uuid(), '2513', 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central'),
  (gen_random_uuid(), '2520', 'Fabricación de armas y municiones'),
  (gen_random_uuid(), '2591', 'Forja, prensado, estampado y laminado de metal; pulvimetalurgia'),
  (gen_random_uuid(), '2592', 'Tratamiento y revestimiento de metales; mecanizado'),
  (gen_random_uuid(), '2593', 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería'),
  (gen_random_uuid(), '2599', 'Fabricación de otros productos elaborados de metal n.c.p.'),
  (gen_random_uuid(), '2610', 'Fabricación de componentes y tableros electrónicos'),
  (gen_random_uuid(), '2620', 'Fabricación de computadoras y de equipo periférico'),
  (gen_random_uuid(), '2630', 'Fabricación de equipos de comunicaciones'),
  (gen_random_uuid(), '2640', 'Fabricación de aparatos electrónicos de consumo'),
  (gen_random_uuid(), '2651', 'Fabricación de equipo de medición, prueba, navegación y control'),
  (gen_random_uuid(), '2652', 'Fabricación de relojes'),
  (gen_random_uuid(), '2660', 'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico'),
  (gen_random_uuid(), '2670', 'Fabricación de instrumentos ópticos y equipo fotográfico'),
  (gen_random_uuid(), '2680', 'Fabricación de soportes magnéticos y ópticos'),
  (gen_random_uuid(), '2711', 'Fabricación de motores, generadores y transformadores eléctricos'),
  (gen_random_uuid(), '2712', 'Fabricación de aparatos de distribución y control de la energía eléctrica'),
  (gen_random_uuid(), '2720', 'Fabricación de pilas, baterías y acumuladores eléctricos'),
  (gen_random_uuid(), '2731', 'Fabricación de hilos y cables eléctricos y de fibra óptica'),
  (gen_random_uuid(), '2732', 'Fabricación de dispositivos de cableado'),
  (gen_random_uuid(), '2733', 'Fabricación de accesorios eléctricos'),
  (gen_random_uuid(), '2740', 'Fabricación de equipos eléctricos de iluminación'),
  (gen_random_uuid(), '2750', 'Fabricación de aparatos de uso doméstico'),
  (gen_random_uuid(), '2790', 'Fabricación de otros tipos de equipo eléctrico n.c.p.'),
  (gen_random_uuid(), '2811', 'Fabricación de motores y turbinas, excepto para aeronaves, vehículos automotores y motocicletas'),
  (gen_random_uuid(), '2812', 'Fabricación de equipos de potencia hidráulica y neumática'),
  (gen_random_uuid(), '2813', 'Fabricación de otras bombas, compresores, grifos y válvulas'),
  (gen_random_uuid(), '2814', 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión'),
  (gen_random_uuid(), '2815', 'Fabricación de hornos, hogares y quemadores industriales'),
  (gen_random_uuid(), '2816', 'Fabricación de equipo de elevación y manipulación'),
  (gen_random_uuid(), '2817', 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)'),
  (gen_random_uuid(), '2818', 'Fabricación de herramientas manuales con motor'),
  (gen_random_uuid(), '2819', 'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.'),
  (gen_random_uuid(), '2821', 'Fabricación de maquinaria agropecuaria y forestal'),
  (gen_random_uuid(), '2822', 'Fabricación de máquinas formadoras de metal y de máquinas herramienta'),
  (gen_random_uuid(), '2823', 'Fabricación de maquinaria para la metalurgia'),
  (gen_random_uuid(), '2824', 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción'),
  (gen_random_uuid(), '2825', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco'),
  (gen_random_uuid(), '2826', 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros'),
  (gen_random_uuid(), '2829', 'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.'),
  (gen_random_uuid(), '2910', 'Fabricación de vehículos automotores y sus motores'),
  (gen_random_uuid(), '2920', 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques'),
  (gen_random_uuid(), '2930', 'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores'),
  (gen_random_uuid(), '3011', 'Construcción de barcos y de estructuras flotantes'),
  (gen_random_uuid(), '3012', 'Construcción de embarcaciones de recreo y deporte'),
  (gen_random_uuid(), '3020', 'Fabricación de locomotoras y de material rodante para ferrocarriles'),
  (gen_random_uuid(), '3030', 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa'),
  (gen_random_uuid(), '3040', 'Fabricación de vehículos militares de combate'),
  (gen_random_uuid(), '3091', 'Fabricación de motocicletas'),
  (gen_random_uuid(), '3092', 'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad'),
  (gen_random_uuid(), '3099', 'Fabricación de otros tipos de equipo de transporte n.c.p.'),
  (gen_random_uuid(), '3100', 'Fabricación de muebles'),
  (gen_random_uuid(), '3110', 'Fabricación de muebles'),
  (gen_random_uuid(), '3120', 'Fabricación de colchones y somieres'),
  (gen_random_uuid(), '3130', 'Fabricación de otros muebles'),
  (gen_random_uuid(), '3140', 'Fabricación de muebles de oficina y de establecimientos comerciales'),
  (gen_random_uuid(), '3150', 'Fabricación de muebles de cocina'),
  (gen_random_uuid(), '3210', 'Fabricación de joyas, bisutería y artículos conexos'),
  (gen_random_uuid(), '3211', 'Fabricación de joyas y artículos conexos'),
  (gen_random_uuid(), '3212', 'Fabricación de bisutería y artículos conexos'),
  (gen_random_uuid(), '3220', 'Fabricación de instrumentos musicales'),
  (gen_random_uuid(), '3230', 'Fabricación de artículos y equipo para la práctica del deporte'),
  (gen_random_uuid(), '3240', 'Fabricación de juegos, juguetes y rompecabezas'),
  (gen_random_uuid(), '3250', 'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos'),
  (gen_random_uuid(), '3290', 'Otras industrias manufactureras n.c.p.'),
  (gen_random_uuid(), '3311', 'Mantenimiento y reparación especializado de productos elaborados en metal'),
  (gen_random_uuid(), '3312', 'Mantenimiento y reparación especializado de maquinaria y equipo'),
  (gen_random_uuid(), '3313', 'Mantenimiento y reparación especializado de equipo electrónico y óptico'),
  (gen_random_uuid(), '3314', 'Mantenimiento y reparación especializado de equipo eléctrico'),
  (gen_random_uuid(), '3315', 'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas'),
  (gen_random_uuid(), '3319', 'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.'),
  (gen_random_uuid(), '3320', 'Instalación especializada de maquinaria y equipo industrial'),

  -- D. Suministro de electricidad, gas, vapor y aire acondicionado
  (gen_random_uuid(), '3511', 'Generación de energía eléctrica'),
  (gen_random_uuid(), '3512', 'Transmisión de energía eléctrica'),
  (gen_random_uuid(), '3513', 'Distribución de energía eléctrica'),
  (gen_random_uuid(), '3514', 'Comercialización de energía eléctrica'),
  (gen_random_uuid(), '3520', 'Producción de gas; distribución de combustibles gaseosos por tuberías'),
  (gen_random_uuid(), '3530', 'Suministro de vapor y aire acondicionado'),

  -- E. Distribución de agua; evacuación y tratamiento de aguas residuales
  (gen_random_uuid(), '3600', 'Captación, tratamiento y distribución de agua'),
  (gen_random_uuid(), '3700', 'Evacuación y tratamiento de aguas residuales'),
  (gen_random_uuid(), '3811', 'Recolección de desechos no peligrosos'),
  (gen_random_uuid(), '3812', 'Recolección de desechos peligrosos'),
  (gen_random_uuid(), '3821', 'Tratamiento y disposición de desechos no peligrosos'),
  (gen_random_uuid(), '3822', 'Tratamiento y disposición de desechos peligrosos'),
  (gen_random_uuid(), '3830', 'Recuperación de materiales'),
  (gen_random_uuid(), '3900', 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos'),

  -- F. Construcción
  (gen_random_uuid(), '4111', 'Construcción de edificios residenciales'),
  (gen_random_uuid(), '4112', 'Construcción de edificios no residenciales'),
  (gen_random_uuid(), '4210', 'Construcción de carreteras y vías de ferrocarril'),
  (gen_random_uuid(), '4220', 'Construcción de proyectos de servicio público'),
  (gen_random_uuid(), '4290', 'Construcción de otras obras de ingeniería civil'),
  (gen_random_uuid(), '4311', 'Demolición'),
  (gen_random_uuid(), '4312', 'Preparación del terreno'),
  (gen_random_uuid(), '4321', 'Instalaciones eléctricas'),
  (gen_random_uuid(), '4322', 'Instalaciones de fontanería, calefacción y aire acondicionado'),
  (gen_random_uuid(), '4329', 'Otras instalaciones especializadas'),
  (gen_random_uuid(), '4330', 'Terminación y acabado de edificios y obras de ingeniería civil'),
  (gen_random_uuid(), '4390', 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil'),

  -- G. Comercio al por mayor y al por menor
  (gen_random_uuid(), '4511', 'Comercio de vehículos automotores nuevos'),
  (gen_random_uuid(), '4512', 'Comercio de vehículos automotores usados'),
  (gen_random_uuid(), '4520', 'Mantenimiento y reparación de vehículos automotores'),
  (gen_random_uuid(), '4530', 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores'),
  (gen_random_uuid(), '4541', 'Comercio de motocicletas y de sus partes, piezas y accesorios'),
  (gen_random_uuid(), '4542', 'Mantenimiento y reparación de motocicletas y de sus partes y piezas'),
  (gen_random_uuid(), '4610', 'Comercio al por mayor a cambio de una retribución o por contrata'),
  (gen_random_uuid(), '4620', 'Comercio al por mayor de materias primas agropecuarias y animales vivos'),
  (gen_random_uuid(), '4631', 'Comercio al por mayor de productos alimenticios'),
  (gen_random_uuid(), '4632', 'Comercio al por mayor de bebidas y tabaco'),
  (gen_random_uuid(), '4641', 'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico'),
  (gen_random_uuid(), '4642', 'Comercio al por mayor de prendas de vestir'),
  (gen_random_uuid(), '4643', 'Comercio al por mayor de calzado'),
  (gen_random_uuid(), '4644', 'Comercio al por mayor de aparatos y equipo de uso doméstico'),
  (gen_random_uuid(), '4645', 'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador'),
  (gen_random_uuid(), '4649', 'Comercio al por mayor de otros utensilios domésticos n.c.p.'),
  (gen_random_uuid(), '4651', 'Comercio al por mayor de computadores, equipo periférico y programas de informática'),
  (gen_random_uuid(), '4652', 'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones'),
  (gen_random_uuid(), '4653', 'Comercio al por mayor de maquinaria y equipo agropecuarios'),
  (gen_random_uuid(), '4659', 'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.'),
  (gen_random_uuid(), '4661', 'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos'),
  (gen_random_uuid(), '4662', 'Comercio al por mayor de metales y productos metalíferos'),
  (gen_random_uuid(), '4663', 'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio'),
  (gen_random_uuid(), '4664', 'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario'),
  (gen_random_uuid(), '4665', 'Comercio al por mayor de desperdicios, desechos y chatarra'),
  (gen_random_uuid(), '4669', 'Comercio al por mayor de otros productos n.c.p.'),
  (gen_random_uuid(), '4690', 'Comercio al por mayor no especializado'),
  (gen_random_uuid(), '4711', 'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco'),
  (gen_random_uuid(), '4719', 'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos'),
  (gen_random_uuid(), '4721', 'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados'),
  (gen_random_uuid(), '4722', 'Comercio al por menor de leche, productos lácteos y huevos'),
  (gen_random_uuid(), '4723', 'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar'),
  (gen_random_uuid(), '4724', 'Comercio al por menor de bebidas y productos del tabaco'),
  (gen_random_uuid(), '4729', 'Comercio al por menor de otros productos alimenticios n.c.p.'),
  (gen_random_uuid(), '4731', 'Comercio al por menor de combustible para automotores'),
  (gen_random_uuid(), '4732', 'Comercio al por menor de lubricantes, aditivos y productos de limpieza para vehículos automotores'),
  (gen_random_uuid(), '4741', 'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones'),
  (gen_random_uuid(), '4742', 'Comercio al por menor de equipos y aparatos de sonido y de video'),
  (gen_random_uuid(), '4751', 'Comercio al por menor de productos textiles en establecimientos especializados'),
  (gen_random_uuid(), '4752', 'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio'),
  (gen_random_uuid(), '4753', 'Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos'),
  (gen_random_uuid(), '4754', 'Comercio al por menor de electrodomésticos y gasodomésticos'),
  (gen_random_uuid(), '4755', 'Comercio al por menor de artículos y utensilios de uso doméstico'),
  (gen_random_uuid(), '4759', 'Comercio al por menor de otros artículos domésticos en establecimientos especializados'),
  (gen_random_uuid(), '4761', 'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio'),
  (gen_random_uuid(), '4762', 'Comercio al por menor de artículos deportivos'),
  (gen_random_uuid(), '4769', 'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p.'),
  (gen_random_uuid(), '4771', 'Comercio al por menor de prendas de vestir y sus accesorios'),
  (gen_random_uuid(), '4772', 'Comercio al por menor de todo tipo de calzado y artículos de cuero'),
  (gen_random_uuid(), '4773', 'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador'),
  (gen_random_uuid(), '4774', 'Comercio al por menor de otros productos nuevos en establecimientos especializados'),
  (gen_random_uuid(), '4775', 'Comercio al por menor de artículos de segunda mano'),
  (gen_random_uuid(), '4781', 'Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles'),
  (gen_random_uuid(), '4782', 'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles'),
  (gen_random_uuid(), '4789', 'Comercio al por menor de otros productos en puestos de venta móviles'),
  (gen_random_uuid(), '4790', 'Comercio al por menor no realizado en establecimientos, puestos de venta o mercados'),

  -- H. Transporte y almacenamiento
  (gen_random_uuid(), '4911', 'Transporte férreo de pasajeros'),
  (gen_random_uuid(), '4912', 'Transporte férreo de carga'),
  (gen_random_uuid(), '4921', 'Transporte de pasajeros'),
  (gen_random_uuid(), '4922', 'Transporte de carga por carretera'),
  (gen_random_uuid(), '4930', 'Transporte por tuberías'),
  (gen_random_uuid(), '5011', 'Transporte de pasajeros marítimo y de cabotaje'),
  (gen_random_uuid(), '5012', 'Transporte de carga marítimo y de cabotaje'),
  (gen_random_uuid(), '5021', 'Transporte fluvial de pasajeros'),
  (gen_random_uuid(), '5022', 'Transporte fluvial de carga'),
  (gen_random_uuid(), '5111', 'Transporte aéreo nacional de pasajeros'),
  (gen_random_uuid(), '5112', 'Transporte aéreo internacional de pasajeros'),
  (gen_random_uuid(), '5121', 'Transporte aéreo nacional de carga'),
  (gen_random_uuid(), '5122', 'Transporte aéreo internacional de carga'),
  (gen_random_uuid(), '5210', 'Almacenamiento y depósito'),
  (gen_random_uuid(), '5221', 'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre'),
  (gen_random_uuid(), '5222', 'Actividades de puertos y servicios complementarios para el transporte acuático'),
  (gen_random_uuid(), '5223', 'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo'),
  (gen_random_uuid(), '5310', 'Actividades postales nacionales'),
  (gen_random_uuid(), '5320', 'Actividades de mensajería'),

  -- I. Alojamiento y servicios de comida
  (gen_random_uuid(), '5511', 'Alojamiento en hoteles'),
  (gen_random_uuid(), '5512', 'Alojamiento en apartahoteles'),
  (gen_random_uuid(), '5513', 'Alojamiento en centros vacacionales'),
  (gen_random_uuid(), '5514', 'Alojamiento rural'),
  (gen_random_uuid(), '5519', 'Otros tipos de alojamiento para visitantes'),
  (gen_random_uuid(), '5520', 'Actividades de zonas de camping y parques para vehículos recreacionales'),
  (gen_random_uuid(), '5590', 'Otros tipos de alojamiento n.c.p.'),
  (gen_random_uuid(), '5611', 'Expendio a la mesa de comidas preparadas'),
  (gen_random_uuid(), '5612', 'Expendio por autoservicio de comidas preparadas'),
  (gen_random_uuid(), '5613', 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento'),
  (gen_random_uuid(), '5619', 'Otros tipos de expendio de comidas preparadas n.c.p.'),
  (gen_random_uuid(), '5621', 'Catering para eventos'),
  (gen_random_uuid(), '5629', 'Actividades de otros servicios de comidas'),
  (gen_random_uuid(), '5630', 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento'),

  -- J. Información y comunicaciones
  (gen_random_uuid(), '5811', 'Edición de libros'),
  (gen_random_uuid(), '5812', 'Edición de directorios y listas de correo'),
  (gen_random_uuid(), '5813', 'Edición de periódicos, revistas y otras publicaciones periódicas'),
  (gen_random_uuid(), '5819', 'Otros trabajos de edición'),
  (gen_random_uuid(), '5820', 'Edición de programas de informática (software)'),
  (gen_random_uuid(), '5911', 'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión'),
  (gen_random_uuid(), '5912', 'Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión'),
  (gen_random_uuid(), '5913', 'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión'),
  (gen_random_uuid(), '5914', 'Actividades de exhibición de películas cinematográficas y videos'),
  (gen_random_uuid(), '5920', 'Actividades de grabación de sonido y edición de música'),
  (gen_random_uuid(), '6010', 'Actividades de programación y transmisión en el servicio de radiodifusión sonora'),
  (gen_random_uuid(), '6020', 'Actividades de programación y transmisión de televisión'),
  (gen_random_uuid(), '6110', 'Actividades de telecomunicaciones alámbricas'),
  (gen_random_uuid(), '6120', 'Actividades de telecomunicaciones inalámbricas'),
  (gen_random_uuid(), '6130', 'Actividades de telecomunicación satelital'),
  (gen_random_uuid(), '6190', 'Otras actividades de telecomunicaciones'),
  (gen_random_uuid(), '6201', 'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación)'),
  (gen_random_uuid(), '6202', 'Actividades de consultoría informática y actividades de administración de instalaciones informáticas'),
  (gen_random_uuid(), '6209', 'Otras actividades de tecnologías de información y servicios informáticos'),
  (gen_random_uuid(), '6311', 'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas'),
  (gen_random_uuid(), '6312', 'Portales web'),
  (gen_random_uuid(), '6391', 'Actividades de agencias de noticias'),
  (gen_random_uuid(), '6399', 'Otras actividades de servicio de información n.c.p.'),

  -- K. Actividades financieras y de seguros
  (gen_random_uuid(), '6411', 'Banca Central'),
  (gen_random_uuid(), '6412', 'Bancos comerciales'),
  (gen_random_uuid(), '6421', 'Actividades de las corporaciones financieras'),
  (gen_random_uuid(), '6422', 'Actividades de las compañías de financiamiento'),
  (gen_random_uuid(), '6423', 'Banca de desarrollo'),
  (gen_random_uuid(), '6424', 'Actividades de cooperativas financieras'),
  (gen_random_uuid(), '6431', 'Fideicomisos, fondos y entidades financieras similares'),
  (gen_random_uuid(), '6432', 'Fondos de cesantías'),
  (gen_random_uuid(), '6491', 'Leasing financiero (arrendamiento financiero)'),
  (gen_random_uuid(), '6492', 'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario'),
  (gen_random_uuid(), '6499', 'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.'),
  (gen_random_uuid(), '6511', 'Seguros generales'),
  (gen_random_uuid(), '6512', 'Seguros de vida'),
  (gen_random_uuid(), '6521', 'Servicios de seguros sociales de salud'),
  (gen_random_uuid(), '6522', 'Servicios de seguros sociales de riesgos profesionales'),
  (gen_random_uuid(), '6531', 'Régimen de prima media con prestación definida (RPM)'),
  (gen_random_uuid(), '6532', 'Régimen de ahorro individual con solidaridad (RAIS)'),
  (gen_random_uuid(), '6611', 'Administración de mercados financieros'),
  (gen_random_uuid(), '6612', 'Corretaje de valores y de contratos de productos básicos'),
  (gen_random_uuid(), '6613', 'Otras actividades relacionadas con el mercado de valores'),
  (gen_random_uuid(), '6614', 'Actividades de las casas de cambio'),
  (gen_random_uuid(), '6615', 'Actividades de los profesionales de compra y venta de divisas'),
  (gen_random_uuid(), '6619', 'Otras actividades auxiliares de los servicios financieros n.c.p.'),
  (gen_random_uuid(), '6621', 'Actividades de agentes y corredores de seguros'),
  (gen_random_uuid(), '6629', 'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares'),

  -- L. Actividades inmobiliarias
  (gen_random_uuid(), '6810', 'Actividades inmobiliarias realizadas con bienes propios o arrendados'),
  (gen_random_uuid(), '6820', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata'),

  -- M. Actividades profesionales, científicas y técnicas
  (gen_random_uuid(), '6910', 'Actividades jurídicas'),
  (gen_random_uuid(), '6920', 'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria'),
  (gen_random_uuid(), '7010', 'Actividades de administración empresarial'),
  (gen_random_uuid(), '7020', 'Actividades de consultoría de gestión'),
  (gen_random_uuid(), '7110', 'Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica'),
  (gen_random_uuid(), '7120', 'Ensayos y análisis técnicos'),
  (gen_random_uuid(), '7210', 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería'),
  (gen_random_uuid(), '7220', 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades'),
  (gen_random_uuid(), '7310', 'Publicidad'),
  (gen_random_uuid(), '7320', 'Estudios de mercado y encuestas de opinión pública'),
  (gen_random_uuid(), '7410', 'Actividades especializadas de diseño'),
  (gen_random_uuid(), '7420', 'Actividades de fotografía'),
  (gen_random_uuid(), '7490', 'Otras actividades profesionales, científicas y técnicas n.c.p.'),
  (gen_random_uuid(), '7500', 'Actividades veterinarias'),

  -- N. Actividades de servicios administrativos y de apoyo
  (gen_random_uuid(), '7710', 'Alquiler y arrendamiento de vehículos automotores'),
  (gen_random_uuid(), '7721', 'Alquiler y arrendamiento de equipo recreativo y deportivo'),
  (gen_random_uuid(), '7722', 'Alquiler de videos y discos'),
  (gen_random_uuid(), '7729', 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.'),
  (gen_random_uuid(), '7730', 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.'),
  (gen_random_uuid(), '7740', 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor'),
  (gen_random_uuid(), '7810', 'Actividades de agencias de gestión y colocación de empleo'),
  (gen_random_uuid(), '7820', 'Actividades de empresas de servicios temporales'),
  (gen_random_uuid(), '7830', 'Otras actividades de suministro de recurso humano'),
  (gen_random_uuid(), '7911', 'Actividades de las agencias de viaje'),
  (gen_random_uuid(), '7912', 'Actividades de operadores turísticos'),
  (gen_random_uuid(), '7990', 'Otros servicios de reserva y actividades relacionadas'),
  (gen_random_uuid(), '8010', 'Actividades de seguridad privada'),
  (gen_random_uuid(), '8020', 'Actividades de servicios de sistemas de seguridad'),
  (gen_random_uuid(), '8030', 'Actividades de detectives e investigadores privados'),
  (gen_random_uuid(), '8110', 'Actividades combinadas de servicios administrativos de oficina'),
  (gen_random_uuid(), '8121', 'Limpieza general interior de edificios'),
  (gen_random_uuid(), '8129', 'Otras actividades de limpieza de edificios e instalaciones industriales'),
  (gen_random_uuid(), '8130', 'Actividades de paisajismo y servicios de mantenimiento conexos'),
  (gen_random_uuid(), '8211', 'Actividades combinadas de servicios administrativos de oficina'),
  (gen_random_uuid(), '8219', 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina'),
  (gen_random_uuid(), '8220', 'Actividades de centros de llamadas (call center)'),
  (gen_random_uuid(), '8230', 'Organización de convenciones y eventos comerciales'),
  (gen_random_uuid(), '8291', 'Actividades de agencias de cobranza y oficinas de crédito'),
  (gen_random_uuid(), '8292', 'Actividades de envase y empaque'),
  (gen_random_uuid(), '8299', 'Otras actividades de servicio de apoyo a las empresas n.c.p.'),

  -- O. Administración pública y defensa
  (gen_random_uuid(), '8411', 'Actividades legislativas de la administración pública'),
  (gen_random_uuid(), '8412', 'Actividades ejecutivas de la administración pública'),
  (gen_random_uuid(), '8413', 'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales'),
  (gen_random_uuid(), '8421', 'Relaciones exteriores'),
  (gen_random_uuid(), '8422', 'Actividades de defensa'),
  (gen_random_uuid(), '8423', 'Orden público y actividades de seguridad'),
  (gen_random_uuid(), '8424', 'Administración de justicia'),
  (gen_random_uuid(), '8430', 'Actividades de seguridad social'),

  -- P. Educación
  (gen_random_uuid(), '8511', 'Educación de la primera infancia'),
  (gen_random_uuid(), '8512', 'Educación preescolar'),
  (gen_random_uuid(), '8513', 'Educación básica primaria'),
  (gen_random_uuid(), '8521', 'Educación básica secundaria'),
  (gen_random_uuid(), '8522', 'Educación media académica'),
  (gen_random_uuid(), '8523', 'Educación media técnica y de formación laboral'),
  (gen_random_uuid(), '8530', 'Establecimientos que combinan diferentes niveles de educación'),
  (gen_random_uuid(), '8541', 'Educación técnica profesional'),
  (gen_random_uuid(), '8542', 'Educación tecnológica'),
  (gen_random_uuid(), '8543', 'Educación de instituciones universitarias o de escuelas tecnológicas'),
  (gen_random_uuid(), '8544', 'Educación de universidades'),
  (gen_random_uuid(), '8551', 'Formación académica no formal'),
  (gen_random_uuid(), '8552', 'Enseñanza deportiva y recreativa'),
  (gen_random_uuid(), '8553', 'Enseñanza cultural'),
  (gen_random_uuid(), '8559', 'Otros tipos de educación n.c.p.'),
  (gen_random_uuid(), '8560', 'Actividades de apoyo a la educación'),

  -- Q. Actividades de atención de la salud humana y de asistencia social
  (gen_random_uuid(), '8610', 'Actividades de hospitales y clínicas, con internación'),
  (gen_random_uuid(), '8621', 'Actividades de la práctica médica'),
  (gen_random_uuid(), '8622', 'Actividades de la práctica odontológica'),
  (gen_random_uuid(), '8691', 'Actividades de apoyo diagnóstico'),
  (gen_random_uuid(), '8692', 'Actividades de apoyo terapéutico'),
  (gen_random_uuid(), '8699', 'Otras actividades de atención de la salud humana'),
  (gen_random_uuid(), '8710', 'Actividades de atención residencial medicalizada'),
  (gen_random_uuid(), '8720', 'Actividades de atención residencial, para el cuidado de pacientes con retraso mental, enfermedad mental y consumo de sustancias psicoactivas'),
  (gen_random_uuid(), '8730', 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas'),
  (gen_random_uuid(), '8790', 'Otras actividades de atención en instituciones con alojamiento'),
  (gen_random_uuid(), '8810', 'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas'),
  (gen_random_uuid(), '8890', 'Otras actividades de asistencia social sin alojamiento'),

  -- R. Actividades artísticas, de entretenimiento y recreación
  (gen_random_uuid(), '9001', 'Creación literaria'),
  (gen_random_uuid(), '9002', 'Creación musical'),
  (gen_random_uuid(), '9003', 'Creación teatral'),
  (gen_random_uuid(), '9004', 'Creación audiovisual'),
  (gen_random_uuid(), '9005', 'Artes plásticas y visuales'),
  (gen_random_uuid(), '9006', 'Actividades teatrales'),
  (gen_random_uuid(), '9007', 'Actividades de espectáculos musicales en vivo'),
  (gen_random_uuid(), '9008', 'Otras actividades de espectáculos en vivo n.c.p.'),
  (gen_random_uuid(), '9101', 'Actividades de bibliotecas y archivos'),
  (gen_random_uuid(), '9102', 'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos'),
  (gen_random_uuid(), '9103', 'Actividades de jardines botánicos, zoológicos y reservas naturales'),
  (gen_random_uuid(), '9200', 'Actividades de juegos de azar y apuestas'),
  (gen_random_uuid(), '9311', 'Gestión de instalaciones deportivas'),
  (gen_random_uuid(), '9312', 'Actividades de clubes deportivos'),
  (gen_random_uuid(), '9319', 'Otras actividades deportivas'),
  (gen_random_uuid(), '9321', 'Actividades de parques de atracciones y parques temáticos'),
  (gen_random_uuid(), '9329', 'Otras actividades recreativas y de esparcimiento n.c.p.'),

  -- S. Otras actividades de servicios
  (gen_random_uuid(), '9411', 'Actividades de asociaciones empresariales y de empleadores'),
  (gen_random_uuid(), '9412', 'Actividades de asociaciones profesionales'),
  (gen_random_uuid(), '9420', 'Actividades de sindicatos de empleados'),
  (gen_random_uuid(), '9491', 'Actividades de asociaciones religiosas'),
  (gen_random_uuid(), '9492', 'Actividades de asociaciones políticas'),
  (gen_random_uuid(), '9499', 'Actividades de otras asociaciones n.c.p.'),
  (gen_random_uuid(), '9511', 'Mantenimiento y reparación de computadores y de equipo periférico'),
  (gen_random_uuid(), '9512', 'Mantenimiento y reparación de equipos de comunicación'),
  (gen_random_uuid(), '9521', 'Mantenimiento y reparación de aparatos electrónicos de consumo'),
  (gen_random_uuid(), '9522', 'Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería'),
  (gen_random_uuid(), '9523', 'Reparación de calzado y artículos de cuero'),
  (gen_random_uuid(), '9524', 'Reparación de muebles y accesorios para el hogar'),
  (gen_random_uuid(), '9529', 'Mantenimiento y reparación de otros efectos personales y enseres domésticos'),
  (gen_random_uuid(), '9601', 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel'),
  (gen_random_uuid(), '9602', 'Peluquería y otros tratamientos de belleza'),
  (gen_random_uuid(), '9603', 'Pompas fúnebres y actividades relacionadas'),
  (gen_random_uuid(), '9609', 'Otras actividades de servicios personales n.c.p.'),

  -- T. Actividades de los hogares como empleadores
  (gen_random_uuid(), '9700', 'Actividades de los hogares individuales como empleadores de personal doméstico'),
  (gen_random_uuid(), '9810', 'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio'),
  (gen_random_uuid(), '9820', 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio'),

  -- U. Actividades de organizaciones y entidades extraterritoriales
  (gen_random_uuid(), '9900', 'Actividades de organizaciones y entidades extraterritoriales')
ON CONFLICT (code) DO NOTHING;
